version: '3.8'

services:
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "18080:8080"
    environment:
      - KAFKA_BROKERS=host.docker.internal:9094  # Use host-gateway on Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
