springdoc:
  writer-with-order-by-keys: true
  api-docs:
    path: /v1.0.0/api-docs
    enabled: true
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: false
    operationsSorter: alpha
    tagsSorter: alpha
